spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 210446
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
